name: VPT Punch Out

on:
  schedule:
    - cron: '0 16 * * 1-5'  # 4:00 PM UTC = 9:30 PM IST, Mon–Fri
  workflow_dispatch:

jobs:
  punchout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run VPT Punch-Out Script
        env:
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_PASS: ${{ secrets.USER_PASS }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: python main.py
