name: VPT Punch Out

on:
  schedule:
    - cron: '30 14 * * 1-5'  # ✅ 8:00 PM IST = 14:30 UTC
  workflow_dispatch:

jobs:
  punchout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run VPT Punch-Out Script
        env:
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_PASS: ${{ secrets.USER_PASS }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: python main.py
